name: QuickMath_Kids
description: "A new Flutter project."
publish_to: 'none' 

version: 2.0.0+5

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.14.1
  confetti: ^0.8.0
  share_plus: ^10.1.3
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  workmanager: ^0.5.2
  shared_preferences: ^2.5.1
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/QuickMath_Kids_logo.png
  uses-material-design: true
