name: QuickMath_Kids
description: ""
publish_to: 'none'

version: 3.1.2+15

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.14.1
  confetti: ^0.8.0
  share_plus: ^10.1.3
  pdf: ^3.11.1
  firebase_core: ^3.10.1
  shared_preferences: ^2.4.8
  in_app_purchase: ^3.2.1
  flutter_secure_storage: ^9.2.4
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/QuickMath_Kids_logo.png
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF" # White background for light mode
  image: assets/QuickMath_Kids_Logo.png
  color_dark: "#000000" # Black background for dark mode
  image_dark: assets/QuickMath_Kids_Logo.png
  fullscreen: true