name: QuickMath_Kids
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.14.1
  confetti: ^0.8.0
  share_plus: ^10.1.3
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/QuickMath_Kids_logo.png
  uses-material-design: true
